### PR TITLE
allowing ops with NOASSERTION

### PR DESCRIPTION
**Pull request by ignacionr**
Related to the discussion started at https://github.com/clearlydefined/service/issues/461 (resolves as decided over meeting)

### CODE REVIEW

**Comment by jeffmcaffer** [comment]
Hmmm, I have to take back my agreement on this (from the call). This change in `merge` will break other scenarios. For example, if one tool can't figure out the license but another can, we want to take the good result. Otherwise we'll always be dragged down to the level of the **worst** tool. The lines deleted here were specifically added to address that scenario.

I suspect the root cause of the cited issue (#461) is actually elsewhere. The reduction algorithm should be simplifying the `NOASSERTION OR NOASSERTION`. And if that it merged with `Ruby` by the current code then it should just end up as `Ruby`.

The key logic difference is where we have multiple tools looking at the same thing and having different outcomes. There the `NOASSERTTIONS` should be ignored. In the scenario where we are aggregating license values (e.g., gathering all the licenses from all the files) then we have "best effort" values that are `NOASSERTION` and that value should be retained. Not sure if we have that case and/or what we do there if we do.

**Comment by ignacionr** [comment]
Actually, I do understand and I thought this would have been the outcome of our conversation on Monday (there were those efforts from 3 months ago, towards explicitly absorbing NOASSERTION values).

As for the cases you describe, there are tests which are currently passing.

My suggestion is to close this, without committing any changes for now, since I suspect the situation was derived from our handling of curations on licenses (which went into merging, but we now will only override).

Other than that, we could do any or all of the following:
- Add a configuration item for the SPDX module (which is independent) so it defaults to absorbing any NOASSERTION (as it does) but allows for not doing so (it might be useful).
- Maybe remove tests which use values that are not viable, such as combining "Ruby OR NOASSERTION" with something else (there is no current way that we can get automatically to "Ruby OR NOASSERTION").

Thanks for stopping by and reviewing this one.

**Comment by jeffmcaffer** [comment]
Do you think the original problem still occurs? Would be good to track down the root cause if so. Otherwise, +1 for closing.

**Comment by ignacionr** [comment]
I believe it should not occur after we commit the new merge strategy for merging. Once we do, and re-harvest, we can be sure.

**Pull request closed without merging**
