### PR TITLE
Update spdx license related dependencies

### PR DESCRIPTION
**Pull request by qtomlinson**
- Update spdx license related dependencies to the latest versions
- Update lockfile version to v3, same version as service and crawler for consistency
- Run npm update

### CODE REVIEW

**Review by capfei — APPROVED** [review]

**Comment by qtomlinson** [comment]
@elrayle @ljones140 We have updated the version.  The new version will need to be released.  See [release instruction](https://github.com/clearlydefined/spdx?tab=readme-ov-file#release)

**Comment by ljones140** [comment]
I tried to do this. I have access to NPM credentials.

But I'm not on the email group that gets the otc 😓

**Comment by jeffmendoza** [comment]
For "internal" npm packages, should we migrate to using GitHub Packges instead of the central npm? Some docs: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

Would need a workflow like this:
```
name: NPM Publish
on: workflow_dispatch
permissions:
  contents: read
  packages: write # To publish npm package to GitHub Packages
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@org'
      - run: npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Then consume like so:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-packages-from-other-organizations

**Comment by ljones140** [comment]
I've tried to get into the outlook account to get the OTC but I can't.

As Outlook sends another OTC to some specific MSFT users.

So this will take longer than expected

**Comment by ljones140** [comment]
@qtomlinson to unblock you I've deployed the package to GitHub packages as @jeffmendoza describes above.

https://github.com/clearlydefined/spdx/pkgs/npm/spdx

Added a workflow that's triggered on release here https://github.com/clearlydefined/spdx/pull/32

Can you use the package from the registry?

I'm not sure if this creates a conflict with the version on NPM. 
If it's a problem I can ask for it to be removed.

**Comment by elrayle** [comment]
@qtomlinson @ljones140 Do we have any information on whether there are consumers of this outside the ClearlyDefined project?

A couple of thoughts if this is the case or we don't have a way to know...
* Is there a path to deprecate the NPM version?
* Is it possible to deploy to both for a period of time (e.g. two months or the next release, whichever is longer)? _I know deploying to NPM is blocked at the moment, but if we can get the info from @mpcen, it would be good to have in both places for a while._

**Comment by qtomlinson** [comment]
@elrayle https://www.npmjs.com/package/@clearlydefined/spdx shows weekly download of 61.

**Comment by ljones140** [comment]
@elrayle I'll ask @mpcen about deploying to NPM.

**Pull request merged**
